- name: Launch EC2 Instances for Configuring Kubernetes Cluster.
  hosts: localhost
  vars_files: 
       - secure.yml
  tasks: 
  - name: Launch EC2 Instance For Setting Up Kubernetes Master Node.
    ec2:
      key_name: "hadoopkey"
      instance_type: "t2.micro"
      image: "ami-010aff33ed5991201"
      wait: yes
      count: 1
      vpc_subnet_id: "subnet-1b053f73"
      region: "ap-south-1"
      state: present
      group_id: "sg-0945e4c25c779a192"
      assign_public_ip: yes
      instance_tags:
        Name: "Master"
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}"
    register: Master

  - name: Launch- EC2 Instance For Setting Up Kubernetes Slave.
    ec2:
      key_name: "hadoopkey"
      instance_type: "t2.micro"
      image: "ami-010aff33ed5991201"
      wait: yes
      count: 1
      vpc_subnet_id: "subnet-1b053f73"
      region: "ap-south-1"
      state: present
      group_id: "sg-0945e4c25c779a192"
      assign_public_ip: yes
      instance_tags:
        Name: "Slave"
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}" 
    register: Slave                                                                                                                               

  - name: Update Inventory File
    blockinfile:
              dest: "/myinventory/hosts.txt"
              block: |
                        [Master]
                        {{ Master.instances[0].public_ip }} ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/root/hadoopkey.pem
                          
                        [Slave]
                        {{ Slave.instances[0].public_ip }} ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/root/hadoopkey.pem
